// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PROJECT_NAME = 'wedding_planner';
  static const String PROJECT_VERSION = '1.0.0+1';
  static const String CATERING = 'assets/images/catering.jpg';
  static const String CITY_GARDENS = 'assets/images/city_gardens.jpg';
  static const String GRAND_BALLROOM = 'assets/images/grand_ballroom.jpg';
  static const String HONEYMOON = 'assets/images/honeymoon.jpg';
  static const String ICON = 'assets/images/icon.jpg';
  static const String LOGO = 'assets/images/logo.png';
  static const String MEHENDI = 'assets/images/mehendi.jpg';
  static const String MOUNTAIN_VIEW_RESORT = 'assets/images/mountain_view_resort.jpg';
  static const String PHOTOGRAPHY = 'assets/images/photography.jpg';
  static const String RUSTIC_MANOR = 'assets/images/rustic_manor.jpg';
  static const String SANGEET = 'assets/images/sangeet.jpg';
  static const String THE_LAKE_HOUSE = 'assets/images/the_lake_house.jpg';
  static const String VENUE = 'assets/images/venue.jpg';
}
